<% project_name = 'team_player' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= team_player %>_development

test:
  <<: *default
  database: <%= team_player %>_test
